package it.polimi.ingsw.client.ui.cli.menus;

public enum GameActions {
    TIDY_WAREHOUSE, BUY_MARBLES, DEPOSIT_RESOURCES, TWO_LEADERS, ACTIVATE_LEADER,THROW_LEADER,SELECT_CARD, BUY_CARD, ACQUIRE_CARD, WAITING, MENU, END_TURN;
}
