package it.polimi.ingsw.client.ui.gui;

public enum LogUpdates {

    TURN, BUY_MARKET, BUY_DEV, ABILITY_ACTIVATION, CARD_THROW, PRODUCTION_ACTIVATED, DEV_NOT_RICH, SOLO_DISCARD, BLACK_CROSS, DISCONNECTION, RECONNECTION, CHOOSE_WHITE, HES_RUNNING_AWAY;

}
